/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as DaylightSavingRouteImport } from './routes/daylight-saving'
import { Route as WorldClocksRouteImport } from './routes/world-clocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DaylightSavingRoute = DaylightSavingRouteImport.update({
  id: '/daylight-saving',
  path: '/daylight-saving',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldClocksRoute = WorldClocksRouteImport.update({
  id: '/world-clocks',
  path: '/world-clocks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/daylight-saving': typeof DaylightSavingRoute
  '/world-clocks': typeof WorldClocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/daylight-saving': typeof DaylightSavingRoute
  '/world-clocks': typeof WorldClocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/daylight-saving': typeof DaylightSavingRoute
  '/world-clocks': typeof WorldClocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/converter' | '/daylight-saving' | '/world-clocks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/converter' | '/daylight-saving' | '/world-clocks'
  id: '__root__' | '/' | '/converter' | '/daylight-saving' | '/world-clocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConverterRoute: typeof ConverterRoute
  DaylightSavingRoute: typeof DaylightSavingRoute
  WorldClocksRoute: typeof WorldClocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daylight-saving': {
      id: '/daylight-saving'
      path: '/daylight-saving'
      fullPath: '/daylight-saving'
      preLoaderRoute: typeof DaylightSavingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-clocks': {
      id: '/world-clocks'
      path: '/world-clocks'
      fullPath: '/world-clocks'
      preLoaderRoute: typeof WorldClocksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConverterRoute: ConverterRoute,
  DaylightSavingRoute: DaylightSavingRoute,
  WorldClocksRoute: WorldClocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
